language: python
virtualenv:
    system_site_packages: true
python:
    - "2.7"
before_install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install python-tk python-matplotlib python-sklearn python-scipy"
install: 
    - "pip install cython"
    - "python -vc \"import nose; print nose.__version__\""
    - "python -c \"import sys; print sys.path\""
    - "python setup.py develop"
    - "python -vc \"import nose; print nose.__version__\""
    - "python -c \"import sys; print sys.path\""
script: "nosetests tests --logging-clear-handlers -v"
