language: python
virtualenv:
    system_site_packages: true
python:
    - "2.7"
before_install:
    - "sudo apt-get install python-tk python-matplotlib python-sklearn python-scipy cython"
install: 
    - "python setup.py develop"
script: "xvfb-run --server-args=\"-screen 0 1024x768x24\" nosetests tests --logging-clear-handlers -v"
